paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  blog:
    path: content/blog
    glob:
      - '!_index.md'
    name: Blog
    icon: post_add
    disable_url: false
    description: ''
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      Blog Post:
        path: schemas/blog-post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
      Customer Story:
        path: schemas/customer-story.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
  products:
    path: content/products
    glob:
      - '!_index.md'
    name: Products
    icon: inventory_2
    disable_url: false
    description: ''
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  data:
    path: data
    name: Site Elements
    icon: important_devices
    disable_url: true
    description: ''
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    schemas:
  staff_members:
    path: content/staff-members
    glob:
      - '!_index.md'
    name: Staff Members
    icon: groups
    disable_url: false
    description: ''
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
collection_groups:
  - heading: Content
    collections:
      - pages
      - blog
      - products
  - heading: Data Files
    collections:
      - staff_members
      - data
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
